# Generated by Django 4.2.7 on 2023-11-22 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0004_box_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, null=True)),
                ('disponibility', models.CharField(max_length=50, null=True)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.game')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='box',
        ),
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.AddField(
            model_name='booking',
            name='gameinstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.gameinstance'),
        ),
    ]
