# Generated by Django 4.2.7 on 2023-11-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_gameinstance_remove_booking_box_delete_box_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameinstance',
            options={'permissions': (('peut_marque_retourner', 'declarer_unjeu_comme_retourne'),)},
        ),
    ]
